### ISSUE TITLE
Reconsider the package

### ISSUE THREAD

**Issue by samdark** [yiisoft/serializer#19]
There's doubt if the package is needed overall.

# Current use cases

Package          | Case  | Thoughts
----------------|-------|--
data-reponse  | `SerializerInterface::serialize()` used in `JsonDataFormatter` and `XmlDataFormatter` to form response from data. `unserialize()` isn't used. | For this case serializer should be as simple/fast as possible. Formatters are concreate so we can possibly have implementation right there not relying on SerializerInterface (in case it's removed).
yii-queue        | `SerializerInterface` used to get string representation of job message. | There's `MessageSerializerInterface` so removing support for `SerializerInterface` isn't a big loss.

**Comment by phena109** [comment]
This is also the dilemma I have sometimes. Using an interface is clean and organised but feel like overhead we may not need in most case. Not using interface is simpler and more flexible but could quickly get messy.

I think I amqp is the only one I think an interface is really needed. The rest of the cases falls back to what I said above.

Also, has anything changed since?

**Comment by samdark** [comment]
> Also, has anything changed since?

No, not yet.

**Comment by samdark** [comment]
Decided to remove serializer package and its usage.

**Comment by samdark** [comment]
https://github.com/yiisoft/data-response/issues/36

**Comment by samdark** [comment]
https://github.com/yiisoft/yii-queue/issues/91

**Comment by samdark** [comment]
Removed serialized dependency from app templates and queue.

**Comment by viktorprogger** [comment]
There is [one more reference](https://github.com/yiisoft/yii-queue-amqp/blob/7f8aa09351c565964e2ac0eb3e73acfdc2fb2986/src/MessageSerializer.php#L18) reference in the amqp queue driver. 

I see two ways to remove this dependency:

1. We can implement `JsonSerializable` interface in payloads and messages and replace `serialize`/`deserialize` with `json_encode`/`json_decode`.

    Pros: this will make the `queue` package more friendly for cross-system usage  
    Cons: less flexibility as we disallow to implement a custom serializer

2. We can move serializer into the `queue` package.

    Pros: more flexibility  
    Const: the `serializer` package is not removed, it's just moved to another place

**Comment by samdark** [comment]
Variant 1. should be alright.
